particle:
  - gamma
direction:
  azimuth: # degrees
    - 0
  zenith:
    - 0
energy: # MeV
  - 20
polarization:
  x:
    - 0
  y:
    - 0
  z:
    - 0
position: # cm
  x:
    - -1
  y:
    - 0
  z:
    - 0
number_of_events: 50000 # per epoch(total)
batch_size: 2000
type_of_events: good # 'good', 'bad' or 'both'
split_data_ratio: 0.2 # split data on train and valid sets, the value is fraction of validation data
